### PR TITLE
Add first draft of lambdas etc. session (day 2, session 1)

### PR DESCRIPTION
**Pull request by msimberg**
First draft to get some feedback.

I'm still unsure how to best split slides (I currently repeat content between slides only to change part of it for the next slide, has anyone found better ways to do this kind of slides?) but this will do for now. I haven't checked how long these would take, but I most likely have too much content. I'll cut slides out once I'm a bit more sure about the exact content.

I also uncommented `class: lead` (for this session) to avoid having all the content in tiny text in one corner. This puts everything centered which is a bit better, but still not great. Ideally I'd like everything a bit bigger, especially the code samples. Perhaps we can tweak the theme a bit at some point.

### CODE REVIEW

**Comment by fawzi** [comment]
I find the repetitions difficult to follow, in many cases you can simply do a list using * (instead of -), which gets exposed one by one (in html).

With lambdas a usecase common in other languages is iterators/loops which leads to also fold and similar operations.

I saw you discuss a bit the various options, maybe a table and a bit more discussion help: bare function, function with context (lambda/closure) template argument (compile time specific function).

**Comment by msimberg** [comment]
> I find the repetitions difficult to follow, in many cases you can simply do a list using * (instead of -), which gets exposed one by one (in html).

Yep, I agree. I don't like it. I can do that for the bullet points, but what I'd really like is the code snippets being replaced and that I haven't found a good replacement for yet. For now I prefer repetition in favour of nicer end-product.

> With lambdas a usecase common in other languages is iterators/loops which leads to also fold and similar operations.

Yep, I group this into the "algorithms with higher-order functions" use case. `transform`, `reduce`, `scan` all look the same from the "function objects" perspective.
 
> I saw you discuss a bit the various options, maybe a table and a bit more discussion help: bare function, function with context (lambda/closure) template argument (compile time specific function).

That's a good idea, thanks. The more theoretical section towards the end is still quite incomplete.

**Comment by fawzi** [comment]
For me this can be merged, not sure about the approach we want to take, should I merge? Or I give the 👍 and @msimberg merges? We want more approvals,...?

**Comment by msimberg** [comment]
> For me this can be merged, not sure about the approach we want to take, should I merge? Or I give the 👍 and @msimberg merges? We want more approvals,...?

Yep, I'll go ahead and merge this. It's not ready, but it's a start. I mainly wanted to know if you are happy with the direction, but I've already gotten that feedback.

**Pull request merged**
